### ISSUE TITLE
TODO: Finish board.py

### ISSUE THREAD

**Issue by AlexCMueller** [HTStem/UltimaT3#1]
- ~~Create function to play on both classes~~
- ~~Implement win detection~~

Once these two are done we can move on to implementing MCTS.

**Comment by AlexCMueller** [comment]
377d076 created functions to play on the classes, implementation of the UTTT board is nearing completion. Implementation of MCTS should be able to start tomorrow.

**Comment by hanss314** [comment]
Win detection has already been implemented, when do you want to implement the MCTS?
